--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-30-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_BOARD
--------------------------------------------------------

  CREATE TABLE "BOOK_PJ"."TBL_BOARD" 
   (	"BOARDNO" NUMBER(10,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate, 
	"REPLYCNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOK_PJ.TBL_BOARD
SET DEFINE OFF;
Insert into BOOK_PJ.TBL_BOARD (BOARDNO,TITLE,CONTENT,WRITER,REGDATE,UPDATEDATE,REPLYCNT) values (62,'test','tester','gwanung',to_date('22/11/29','RR/MM/DD'),to_date('22/11/29','RR/MM/DD'),0);
Insert into BOOK_PJ.TBL_BOARD (BOARDNO,TITLE,CONTENT,WRITER,REGDATE,UPDATEDATE,REPLYCNT) values (23,'테스트 제목','테스트 내용','tester',to_date('22/11/20','RR/MM/DD'),to_date('22/11/20','RR/MM/DD'),0);
Insert into BOOK_PJ.TBL_BOARD (BOARDNO,TITLE,CONTENT,WRITER,REGDATE,UPDATEDATE,REPLYCNT) values (24,'테스트 제목','테스트 내용','tester',to_date('22/11/20','RR/MM/DD'),to_date('22/11/20','RR/MM/DD'),0);
Insert into BOOK_PJ.TBL_BOARD (BOARDNO,TITLE,CONTENT,WRITER,REGDATE,UPDATEDATE,REPLYCNT) values (25,'테스트 제목','테스트 내용','tester',to_date('22/11/20','RR/MM/DD'),to_date('22/11/20','RR/MM/DD'),1);
Insert into BOOK_PJ.TBL_BOARD (BOARDNO,TITLE,CONTENT,WRITER,REGDATE,UPDATEDATE,REPLYCNT) values (41,'테스트 제목','테스트 내용','tester',to_date('22/11/20','RR/MM/DD'),to_date('22/11/20','RR/MM/DD'),1);
--------------------------------------------------------
--  DDL for Index PK_TBL_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK_PJ"."PK_TBL_BOARD" ON "BOOK_PJ"."TBL_BOARD" ("BOARDNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_BOARD
--------------------------------------------------------

  ALTER TABLE "BOOK_PJ"."TBL_BOARD" ADD CONSTRAINT "PK_TBL_BOARD" PRIMARY KEY ("BOARDNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK_PJ"."TBL_BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
