--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-30-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "BOOK_PJ"."TBL_MEMBER" 
   (	"MEMBERID" VARCHAR2(50 BYTE), 
	"MEMBERPW" VARCHAR2(100 BYTE), 
	"MEMBERNAME" VARCHAR2(30 BYTE), 
	"MEMBERMAIL" VARCHAR2(100 BYTE), 
	"MEMBERADDR1" VARCHAR2(100 BYTE), 
	"MEMBERADDR2" VARCHAR2(100 BYTE), 
	"MEMBERADDR3" VARCHAR2(100 BYTE), 
	"REGDATE" DATE, 
	"POINT" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOK_PJ.TBL_MEMBER
SET DEFINE OFF;
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE,POINT) values ('test','$2a$10$zI/Lronpt8XenrfLK3D7ZOJ5pa2ZKFnoCkRLPXvWyc9EcobovVXla','원관웅','abcd@naver.com','13480','경기 성남시 분당구 대왕판교로 477 (판교동)','ㄹ',to_date('22/11/29','RR/MM/DD'),5000);
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE,POINT) values ('a','$2a$10$2I9YL0Wy0PsVGeP53/4cN.dNzmZz4yRg1CgNNLAVJ/r950UG.3tvK','원관웅','ktx7943@naver.com','39271','경북 구미시 구미중앙로 272 (송정동)','테스트 주소',to_date('22/11/23','RR/MM/DD'),0);
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE,POINT) values ('aaa','$2a$10$VSlLElOzquJ9TK4hKuhD4elHNDEXuuqw5FOb7ADbiTtE/1FTJTsmy','ㅅ','ㅅ','39271','경북 구미시 구미중앙로 272 (송정동)','ㅅ',to_date('22/11/23','RR/MM/DD'),0);
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE,POINT) values ('test2','$2a$10$XueFC.K1LlV5wlsToP1oI.MrPnUrED2/E1b9uvkyVcav00zXGVSQu','원관웅','abcd@naver.com','13480','경기 성남시 분당구 대왕판교로 477 (판교동)','테스트',to_date('22/11/26','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007570
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK_PJ"."SYS_C007570" ON "BOOK_PJ"."TBL_MEMBER" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" ADD PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERADDR3" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERADDR2" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERADDR1" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERMAIL" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERPW" NOT NULL ENABLE);
