--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_CART
--------------------------------------------------------

  CREATE TABLE "BOOK_PJ"."TBL_CART" 
   (	"CARTBNO" NUMBER(20,0), 
	"BNO" NUMBER(20,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DISCOUNT" NUMBER(20,0), 
	"TOTALPRICE" NUMBER(20,0), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"IMAGE" VARCHAR2(300 BYTE), 
	"COUNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOK_PJ.TBL_CART
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007586
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK_PJ"."SYS_C007586" ON "BOOK_PJ"."TBL_CART" ("CARTBNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_CART
--------------------------------------------------------

  ALTER TABLE "BOOK_PJ"."TBL_CART" ADD PRIMARY KEY ("CARTBNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK_PJ"."TBL_CART" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_CART" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_CART" MODIFY ("TOTALPRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_CART" MODIFY ("DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_CART" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_CART" MODIFY ("BNO" NOT NULL ENABLE);
