--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "BOOK_PJ"."TBL_MEMBER" 
   (	"MEMBERID" VARCHAR2(50 BYTE), 
	"MEMBERPW" VARCHAR2(100 BYTE), 
	"MEMBERNAME" VARCHAR2(30 BYTE), 
	"MEMBERMAIL" VARCHAR2(100 BYTE), 
	"MEMBERADDR1" VARCHAR2(100 BYTE), 
	"MEMBERADDR2" VARCHAR2(100 BYTE), 
	"MEMBERADDR3" VARCHAR2(100 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOK_PJ.TBL_MEMBER
SET DEFINE OFF;
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE) values ('test','$2a$10$U4/6gDHKTnmU33hRVjkiaeILVo/lDsw95Iydrhx8b9BOtjYWHphKC','홍길동','abcd@naver.com','38448','경북 경산시 진량읍 대구대로 2','대구대학교',to_date('22/11/21','RR/MM/DD'));
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE) values ('a','$2a$10$2I9YL0Wy0PsVGeP53/4cN.dNzmZz4yRg1CgNNLAVJ/r950UG.3tvK','원관웅','ktx7943@naver.com','39271','경북 구미시 구미중앙로 272 (송정동)','테스트 주소',to_date('22/11/23','RR/MM/DD'));
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE) values ('test2','$2a$10$CFJBNlCAWzo8lay9dwSa9.84O4WYAN/HmFlxxA3h644Y2znFxwgQK','홍','ktx7943@naver.com','39271','경북 구미시 구미중앙로 272 (송정동)','ㄹ',to_date('22/11/23','RR/MM/DD'));
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE) values ('aaa','$2a$10$VSlLElOzquJ9TK4hKuhD4elHNDEXuuqw5FOb7ADbiTtE/1FTJTsmy','ㅅ','ㅅ','39271','경북 구미시 구미중앙로 272 (송정동)','ㅅ',to_date('22/11/23','RR/MM/DD'));
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE) values ('gwanung','$2a$10$DECkjD0e8Po1ynToR5g8S.EEiiMlpOhsBjTykUOYte9XBFB3hRARe','원관웅','abcd@naver.com','38448','경북 경산시 진량읍 대구대로 2','대구대학교',to_date('22/11/23','RR/MM/DD'));
Insert into BOOK_PJ.TBL_MEMBER (MEMBERID,MEMBERPW,MEMBERNAME,MEMBERMAIL,MEMBERADDR1,MEMBERADDR2,MEMBERADDR3,REGDATE) values ('admin','1234','원관웅','ktx7943@naver.com','39271','경북 구미시 구미중앙로 272 (송정동)','1',to_date('22/11/21','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007570
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK_PJ"."SYS_C007570" ON "BOOK_PJ"."TBL_MEMBER" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" ADD PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERADDR3" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERADDR2" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERADDR1" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERMAIL" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK_PJ"."TBL_MEMBER" MODIFY ("MEMBERPW" NOT NULL ENABLE);
